name: Java application

on:
  push:
   branches: [ dev ]
  pull_request:
    branches: [ dev ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ dckr_pat_dQhVxACam4byjxzdEY4GM76fPTE }}" | docker login -u "anshusuroliya" --password-stdin
        docker image build -t anshusuroliya/springboot:latest .
        docker push anshusuroliya/springboot:latest
