name: Java application

on:
  push:
   branches: [ dev ]
  pull_request:
    branches: [ dev ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      env:
          DOCKER_TOKEN: ${{ secrets.DOCKERTOKEN }}
      run: |
        echo ${{ secrets.DOCKERTOKEN }} | docker login -u "anshusuroliya" --password-stdin
        docker build .
        docker push 
